Repository ScriptKiddies-Incorporated/Hangman, pull requests merged in 2019-10, with the labels that each got.

#2 Add gaps for the letters of the words
  Program.cs
Labels: enhancement

#3 Separate Code into relevant files; Improve spacing; Add language choosing option
  DrawUI.cs
  Program.cs
  README.md
Labels: Refactoring, bug fix, documentation, enhancement

#5 Add letter guessing UI and logic
  DrawUI.cs
Labels: enhancement

#8 Check if chosenLetter > 1
  .vs/Hangman/v16/.suo
  .vs/slnx.sqlite
  DrawUI.cs
  bin/Debug/Hangman.exe
  bin/Debug/Hangman.pdb
  obj/Debug/Hangman.csproj.FileListAbsolute.txt
  obj/Debug/Hangman.csprojAssemblyReference.cache
  obj/Debug/Hangman.exe
  obj/Debug/Hangman.pdb
Labels: bug fix

#11 Check if the user has already guessed the chosen letter
  DrawUI.cs
  Program.cs
Labels: bug fix, enhancement
